image: registry.gitlab.com/aca-engine/frontend-base/ngx-backoffice:latest

stages:
    - test
    - build
    - deploy

# Cache node modules for future runs
cache:
    key: aca-general-angular-cache
    paths:
        - node_modules/

variables:
    DOCKER_DRIVER: overlay2
    DEMO_ROUTE: '/demo/aca/backoffice/'
    DEPLOY_FOLDER: 'backoffice'
    DEPLOY_REPO_PATH: 'gitlab.com/aca-engine/deploy/www-template.git'

before_script:
    - BRANCH=$CI_COMMIT_REF_NAME
    - GIT_USER=$GITLAB_USER_NAME
    - GIT_EMAIL=$GITLAB_USER_EMAIL
    - export BRANCH
    - export GIT_USER
    - export GIT_EMAIL
    # Set GIT user to the commit user
    - git config --global user.name $GIT_USER
    - git config --global user.email $GIT_EMAIL
    - git remote set-url origin https://$GITLAB_TOKEN@gitlab.com/$CI_PROJECT_PATH.git

# Add versioning details build from semantic release
versioned_build:
    stage: build
    only:
        refs:
            - master
            - schedules
    except:
        - tags
    artifacts:
        paths:
            - dist/
    script:
        - npm install -g gulp @angular/cli semantic-release --quiet
        - npm run semantic-release
        - /bin/sh ./scripts/build-with-version-tag.sh

# Standalone build of the application
build_app:
    stage: build
    script:
        - npm install -g gulp @angular/cli semantic-release --quiet
        - gulp build --prod --aot
    artifacts:
        paths:
            - dist/
    except:
        - master
        - schedules
        - tags

# Run tests for the application
test_app:
    stage: test
    script:
        - npm install -g gulp @angular/cli --quiet
        - npm install --quiet
        - npm run test:ci
    except:
        - tags

# Deploy demo build of the latest version
deploy_demo:
    stage: deploy
    only:
        refs:
            - deploy
            - dev
            - develop
    script:
        - npm install -g gulp @angular/cli --quiet
        - /bin/sh ./scripts/build-demo.sh

# Deploy build of the latest version
deploy_app:
    stage: deploy
    only:
        refs:
            - master
            - develop
            - schedules
    script:
        - /bin/sh ./scripts/deploy.sh
    except:
        - tags
