image: node:10.15.0
options:
  max-time: 10
pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          artifacts:
            - dist/**
          script: # Modify the commands below to build your repository.
            - npm install
            - npm i natives@1.1.6
            - npm i -g gulp @angular/cli ts-node typescript
            - ./build-demo.sh
            - gulp build --prod --aot
      - step:
          name: Deploy
          script:
            - GIT_USER=$(git log -1 --format='%an')
            - GIT_EMAIL=$(git log -1 --format='%ae')
            - git config --global user.name $GIT_USER
            - git config --global user.email $GIT_EMAIL
            - git clone https://$USER:$PASS@bitbucket.org/aca/${REPO}.git deployment
            - rm -rf deployment/back-office
            - mv dist deployment/back-office
            - cd deployment
            - git add -A
            - git commit -m "[Backoffice UI] Pipeline build `date +'%Y-%m-%d %H:%M:%S'`"
            - git push