image: node:latest
options:
    max-time: 10
pipelines:
    default:
        - step:
              name: Test
              caches:
                  - node
              script:
                  - npm install --quiet
                  - ./scripts/install-chrome.sh
                  - npm run test:ci
    branches:
        develop:
            - step:
                  name: Test
                  caches:
                      - node
                  script:
                      - npm install --quiet
                      - ./scripts/install-chrome.sh
                      - npm run test:ci
            - step:
                  name: Build
                  caches:
                      - node
                  artifacts:
                      - dist/**
                  script:
                      - npm install --quiet
                      - npm install --quiet -g gulp
                      - ./scripts/build-demo.sh
        master:
            - step:
                  name: Test
                  caches:
                      - node
                  script:
                      - npm install --quiet
                      - ./scripts/install-chrome.sh
                      - npm run test:ci
            - step:
                  name: Build
                  caches:
                      - node
                  artifacts:
                      - dist/**
                  script:
                      - npm install --quiet
                      - npm install --quiet -g gulp
                      - gulp build --prod --aot
            - step:
                  name: Deploy
                  script:
                      - ./scripts/deploy.sh
