module.exports = {
    prefix: '',
    important: '#placeos',
    mode: 'jit',
    content: ['./src/**/*.{html,ts,css,scss,sass,less,styl}'],
    darkMode: 'class', // or 'media' or 'class'
    theme: {
        colors: {
            primary: 'var(--primary)',
            'primary-focus': 'var(--primary-focus)',
            'primary-content': 'var(--primary-content)',
            secondary: 'var(--secondary)',
            'secondary-focus': 'var(--secondary-focus)',
            'secondary-content': 'var(--secondary-content)',
            accent: 'var(--accent)',
            'accent-focus': 'var(--accent-focus)',
            'accent-content': 'var(--accent-content)',
            neutral: 'var(--neutral)',
            'neutral-focus': 'var(--neutral-focus)',
            'neutral-content': 'var(--neutral-content)',
            'base-100': 'var(--base-100)',
            'base-200': 'var(--base-200)',
            'base-300': 'var(--base-300)',
            'base-400': 'var(--base-400)',
            'base-content': 'var(--base-content)',
            info: 'var(--info)',
            'info-light': 'var(--info-light)',
            'info-content': 'var(--info-content)',
            success: 'var(--success)',
            'success-light': 'var(--success-light)',
            'success-content': 'var(--success-content)',
            warning: 'var(--warn)',
            'warning-light': 'var(--warn-light)',
            'warning-content': 'var(--warn-content)',
            error: 'var(--error)',
            'error-light': 'var(--error-light)',
            'error-content': 'var(--error-content)',
            white: '#ffffff',
            black: '#000000',
        },
        extend: {
            lineClamp: {
                7: '7',
                8: '8',
                9: '9',
                10: '10',
            },
        },
    },
    variants: {
        extend: {},
    },
    plugins: [],
};
